# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8180
  servlet:
    context-path: /zs-admin

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: 192.168.1.222
    port: 6380
    password: test123     # \u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    timeout: 6000ms  # \u8FDE\u63A5\u8D85\u65F6\u65F6\u957F\uFF08\u6BEB\u79D2\uFF09
    jedis:
      pool:
        max-active: 1000  # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: -1ms      # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-idle: 10      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 5       # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
  freemarker:
    suffix: .html
    request-context-attribute: request

renren:
  cluster: false  #\u96C6\u7FA4\u914D\u7F6E  true\u96C6\u7FA4\u73AF\u5883   false\u5355\u673A\u73AF\u5883\uFF0C\u8FD8\u9700\u6253\u5F00pom.xml\u91CC\u7684spring-session-data-redis\u6CE8\u91CA
  globalSessionTimeout: 3600   #\u5355\u673A\u73AF\u5883\uFF0Csession\u8FC7\u671F\u65F6\u95F4\u4E3A60\u5206\u949F
  redis:
    open: false  #\u662F\u5426\u5F00\u542Fredis\u7F13\u5B58  true\u5F00\u542F   false\u5173\u95ED


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: io.zs.modules.*.entity
  global-config:
    #\u6570\u636E\u5E93\u76F8\u5173\u914D\u7F6E
    db-config:
      #\u4E3B\u952E\u7C7B\u578B  AUTO:"\u6570\u636E\u5E93ID\u81EA\u589E", INPUT:"\u7528\u6237\u8F93\u5165ID", ID_WORKER:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", UUID:"\u5168\u5C40\u552F\u4E00ID UUID";
      id-type: AUTO
      #\u5B57\u6BB5\u7B56\u7565 IGNORED:"\u5FFD\u7565\u5224\u65AD",NOT_NULL:"\u975E NULL \u5224\u65AD"),NOT_EMPTY:"\u975E\u7A7A\u5224\u65AD"
      field-strategy: NOT_NULL
      #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #\u539F\u751F\u914D\u7F6E
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'